@startuml

title "Исправление замечаний с локальной проверкой"

actor "Разработчик 1С"

"Разработчик 1С" -> "Хранилище 1С": первое помещение версии\n для проверки
"Разработчик 1С" -> "GIT сервер": клонирование репозитория
"Разработчик 1С" -> "Локальный GIT репозиторий": открытие в Visual Studio Code\n с плагином SonarLint 
"Разработчик 1С" -> "SonarQube сервер": подключение проекта в VSCode
"SonarQube сервер" -> "Разработчик 1С": подсветка мест для исправления в коде 1С
"Разработчик 1С" -> "Хранилище 1С": Загрузка исправлено кода из файлов

@enduml