@startuml

title Схема работы команды

actor "Релиз менеджер"
actor "Менеджер проекта"
actor "Разрабтчик 1С"

"Разрабтчик 1С" -> "Хранилище 1С" : "Помещение очередной версии"
"Хранилище 1С" -> "Git сервер" : "Запуск репликатора GIT"
"Git сервер" -> "CI сервер": "Оповещение WebHook"
"CI сервер" -> "Агент сборки CI": "Запуск анализа"
"Агент сборки CI" -> "Сервер SonarQube": "Фиксация очередной версии\n результатов анализа"
"Сервер SonarQube" -> "Разрабтчик 1С": оповещение e-mail (slack) о багах
"Сервер SonarQube" -> "Релиз менеджер": оповещение e-mail (slack)\n о превышении порога качества
"Сервер SonarQube" -> "Менеджер проекта": оповещение e-mail (slack)\n о показателях качества проекта
"Разрабтчик 1С" -> "Сервер SonarQube": просмотр рекомендации по исправлению
"Релиз менеджер" -> "Сервер SonarQube": просмотр приоритетов на рефакторинг
"Менеджер проекта" -> "Сервер SonarQube": оценка рисков проекта к передачи заказчику

@enduml
